### ISSUE TITLE
issue while building the application

### ISSUE THREAD

**Issue by iamnaveenoff** [nirajwagh/covid-19_india_android_app#1]
![image](https://user-images.githubusercontent.com/13293139/77832454-46625200-715c-11ea-934e-800062b3c3ba.png)

**Comment by nirajwagh** [comment]
Hello Naveen,
Thanks for reporting the issue. 
On which SDK are you running the app?
I will push an update after resolving the error. 
Meanwhile, you can try running the app on some other version of android.

**Comment by iamnaveenoff** [comment]
just now i cloned the app

**Comment by nirajwagh** [comment]
Some files were not pushed. I have updated the project. It should work fine now. Do let me know if you still get issues.

**Comment by iamnaveenoff** [comment]
it works cool i also need some help in building my app can you please help me  i have emailed you my queries
